# Настройки магических палочек
wands:
  teleport:
    name: "&6Магическая палочка: &eТелепорт"
    lore:
      - "&7Правая кнопка мыши для активации"
      - "&7Телепортирует вас в указанную точку"
    cooldown: 5 # секунды
    range: 50 # блоков
    message: "&aВы телепортировались!"
    
  explosion:
    name: "&6Магическая палочка: &cВзрыв"
    lore:
      - "&7Правая кнопка мыши для активации"
      - "&7Создает взрыв в указанной точке"
    cooldown: 10
    range: 50
    power: 2.0
    message: "&cБум!"
    
  lightning:
    name: "&6Магическая палочка: &eМолния"
    lore:
      - "&7Правая кнопка мыши для активации"
      - "&7Призывает молнию в указанную точку"
    cooldown: 15
    range: 50
    message: "&eМолния ударила!"

# Настройки сообщений
messages:
  prefix: "&8[&6MagicWands&8] &r"
  no-permission: "&cУ вас нет прав для использования этой команды!"
  player-only: "&cЭта команда только для игроков!"
  player-not-found: "&cИгрок не найден!"
  wand-received: "&aВы получили магическую палочку!"
  wand-given: "&aВы выдали магическую палочку игроку %player%"
  cooldown: "&cПодождите %time% секунд перед следующим использованием!"
  unknown-command: "&cНеизвестная подкоманда! Используйте /magicwands help"
  give-usage: "&cИспользование: /magicwands give <игрок> <тип>"
  unknown-wand-type: "&cНеизвестный тип палочки! Доступные типы: %types%"
  help:
    - "&6=== MagicWands Помощь ==="
    - "&e/magicwands give <игрок> <тип> &7- Выдать магическую палочку"
    - "&e/magicwands help &7- Показать это сообщение"
    - "&6======================" 